<?php

namespace Magenest\Forum\Model\ResourceModel\Comment;

use Magenest\Forum\Model\Comment as CommentModel;
use Magenest\Forum\Model\ResourceModel\Comment as CommentResourceModel;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected function _construct()
    {
        $this->_init(CommentModel::class, CommentResourceModel::class);
    }
    protected function _initSelect()
    {
        parent::_initSelect();
        $customer = $this->getTable('customer_entity');
        $this->getSelect()
            ->joinLeft($customer, 'main_table.user_id =' .$customer.'.entity_id',['firstname', 'lastname','email']);
        return $this; // TODO: Change the autogenerated stub
    }
}
