<?php

namespace Magenest\Checkout\Model\ResourceModel\ClaimCoupon;
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'id';


    protected function _construct()
    {
        $this->_init('Magenest\Checkout\Model\ClaimCoupon', 'Magenest\Checkout\Model\ResourceModel\ClaimCoupon');
    }
    protected function _initSelect()
    {
        parent::_initSelect();
        $salesRuleTable = $this->getTable('salesrule');
        $this->addFieldToSelect('customer_id');
        $this->getSelect()
            ->joinLeft($salesRuleTable,'main_table.rule_id = salesrule.rule_id')
            ->joinLeft('salesrule_coupon', 'main_table.coupon_id = salesrule_coupon.coupon_id');
        return $this; // TODO: Change the autogenerated stub
    }

}
