<?php
/**
 * @var \Magenest\CouponCode\Block\MyCoupon $block
 */
$coupon = $block->getCoupon();
/**
 * @var \Magenest\CouponCode\ViewModel\Coupon $viewModel
 */
$viewModel = $block->getViewModel();
$today = $viewModel->getToday();
if ($coupon->getSize() != 0) {
    $count = count($coupon); ?>
    <?php foreach ($coupon as $value) { ?>
        <div id="coupon_magenest">
            <div id="container_coupon">
                <?php
                if (!empty($value->getData('images'))) {
                    $images = $viewModel->handleImage($value->getData('images'));
                } else {
                    $images = $block->getViewFileUrl('Magenest_CouponCode::image/default-coupon.png');
                }?>
                    <div>
                        <img src="<?= $block->escapeHtml($images); ?>"
                             alt="coupon" width="150px" height="150px"/>
                    </div>
                <div id="information_mycoupon" >
                    <strong><?= $block->escapeHtml($value->getData('name')) ?></strong>
                    <?php
                    $description = $value->getData('description');
                    if (strlen($description) <= 120) { ?>
                        <div id="description-coupon">
                            <?= $block->escapeHtml($value->getData('description')) ?>
                        </div>
                    <?php } else {
                        $contentDisplay = substr($description, 0, 120);
                        ?>
                        <div id="description-coupon">
                            <div><?= $block->escapeHtml($contentDisplay) ?>
                                <span class="see-more-coupon"
                                      id="seeMore"
                                      data-bind="scope:'seeMore'">
                                          <span data-bind="click: seeMore.bind($parent,
                                                          '<?= $block->escapeHtml($description) ?>')">
                                               <?= $block->escapeHtml(__('...See more')) ?>
                                          </span>
                                </span>
                            </div>
                        </div>
                    <?php }?>
                    <div class = "usage">
                        <?php
                        $usage = $value->getData('usage_limit');
                        if ($usage == null) { ?>
                            <div class="usage_limit"><?= $block->escapeHtml(__('Usage limit: ')).
                                                        $block->escapeHtml(__('Unlimited')); ?>
                            </div>
                        <?php } else { ?>
                            <div class="usage_limit"><?= $block->escapeHtml(__('Usage limit: ')).
                                                        $block->escapeHtml($usage); ?>
                            </div>
                        <?php } ?>
                        <?php
                        $usageCustomer = $value->getData('usage_per_customer');
                        if ($usageCustomer == null) { ?>
                            <div class="usage_customer"><?= $block->escapeHtml(__('Awarded: ')).
                                                            $block->escapeHtml(__('Unlimited')); ?>
                            </div>
                        <?php } else { ?>
                            <div class="usage_customer"><?= $block->escapeHtml(__('Awarded: ')).
                                                            $block->escapeHtml($usageCustomer); ?>
                            </div>
                        <?php } ?>
                    </div>
                    <div><?php
                    if ($today < strtotime($value->getData('to_date')) + 86400) { ?>
                            <div id="exp-coupon">
                                <?= $block->escapeHtml(__('Exp: ').$block->escapeHtml($value->getData('to_date'))); ?>
                            </div>
                        <?php } elseif ($value->getData('to_date') != null) { ?>
                            <div id="exp-coupon">
                                <?= $block->escapeHtml(__('Exp: ')
                                    .$block->escapeHtml($value->getData('to_date').__(' (Out of date)')))?>
                            </div>
                        <?php } else { ?>
                            <div id="exp-coupon"><?= $block->escapeHtml(__('Exp: ')).
                                                    $block->escapeHtml(__('Unlimited')); ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if ($count%2 == 1) { ?>
        <div class="coupon-magenest" id="coupon_magenest_blank"></div>
    <?php } ?>
<?php } ?>
<?php if ($block->getPagerHtml()): ?>
    <?= $block->getPagerHtml(); ?>
<?php endif ?>
<script type="text/x-magento-init">
            {
                "#seeMore": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "seeMore": {
                                "component": "Magenest_CouponCode/js/coupon/action"
                            }
                        }
                    }
                }
            }
</script>


