
    <div id="modal-promotion" style="display:none;">

        <h1> SALE </h1>
        <img src="http://example.com/media/wysiwyg/sale/sale-mens.jpg" alt=""/>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "modal_promotion": {
                            "component": "Magenest_Frontend/js/modal_promotion"
                        }
                     }
                }
            }
        }
    </script>
