<h2>Blog List</h2>
<table>
    <tr>
        <th>Author</th>
        <th>Description</th>
        <th>Title</th>
        <th>Content</th>
        <th>Status</th>
        <th>User role</th>
    </tr>
    <?php foreach ($block->getBlog() as $blog): ?>
        <tr>
            <td><?php echo $blog->getFirstname() ?></td>
            <td><?php echo $blog->getDescription() ?></td>
            <td><?php echo $blog->getTitle() ?></td>
            <td><?php echo $blog->getContent()?></td>
            <td><?php echo $blog->getStatus()?></td>
            <td><?php echo $blog->getUsername() ?></td>

        </tr>

    <?php endforeach; ?>

</table>
