<h2>Blog List</h2>
<table>
    <tr>
        <th>Author</th>
        <th>Description</th>
        <th>Title</th>
        <th>Content</th>
        <th>Status</th>
        <th>User role</th>
        <th>Action</th>

    </tr>
    <?php foreach ($block->getBlog() as $blog): ?>

        <tr>
            <td><?php echo $blog->getFirstname() ?></td>
            <td><?php echo $blog->getDescription() ?></td>
            <td><?php echo $blog->getTitle() ?></td>
            <td><?php echo $blog->getContent()?></td>
            <td><?php echo $blog->getStatus()?></td>
            <td><?php echo $blog->getUsername() ?></td>
            <td><a href="https://example.com/blog/view/id/<?php echo $blog->getId() ?>">View</a></td>

        </tr>

    <?php endforeach; ?>

</table>
