<?php
/** @var  $block \Magenest\NotificationBox\Block\Notification\Notification */
/** show icon notification when customer is login */
?>
<div class="notificationBox" data-bind="scope: 'notificationBox'" hidden>
    <div class="magenest-notification" data-bind="visible: visibleNotificationBox">
        <span class="magenest-notification-icon" >
            <img src="<?= $block->escapeHtml($block
                ->getViewFileUrl('Magenest_NotificationBox::image/noti.png'));?>"
                 alt="">
        </span>
        <span class="magenest-notification-count" data-bind="text: totalNotificationUnread"></span>
        <div >
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "notificationBox": {
                        "component": "Magenest_NotificationBox/js/notification/notification",
                        "template" : "Magenest_NotificationBox/notification",
                        "config": {
                                    "url"                           :
                                        "<?= $block->escapeHtml($block->getUrl("notibox/customer/notification"))?>",
                                    "currentUrl"                    :
                                        "<?= $block->escapeHtml($block->getUrl())?>",
                                    "backgroundColorValue"          :
                                        "<?= $block->escapeHtml($block->getThemeColor())?>",
                                    "boxPositionClass"              :
                                        "<?= $block->escapeHtml($block->getBoxPosition())?>",
                                    "notificationBoxWidth"          :
                                        "<?= $block->escapeHtml($block->getBoxWidth())?>"
                        }
                    }
                }
            }
        }
    }
</script>

