<?php

namespace Magenest\CouponCode\Model\ResourceModel\ClaimCoupon;

use Magenest\CouponCode\Model\ClaimCoupon as ClaimedCouponModel;
use Magenest\CouponCode\Model\ResourceModel\ClaimCoupon as ClaimedCouponResourceModel;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    /**
     * Init collection
     */
    protected function _construct()
    {
        $this->_init(ClaimedCouponModel::class, ClaimedCouponResourceModel::class);
    }

    /**
     * Join with salesrule table and salesrule_coupon table
     *
     * @return Collection
     */
    protected function _initSelect()
    {
        parent::_initSelect();
        $salesRuleCoupon = $this->getTable('salesrule_coupon');
        $salesRuleTable = $this->getTable('salesrule');
        $this->addFieldToSelect('customer_id')
            ->addFieldToSelect('coupon_id');
        $this->getSelect()
            ->group('main_table.rule_id')
            ->joinLeft($salesRuleTable, 'main_table.rule_id =' .$salesRuleTable.'.rule_id')
            ->joinLeft($salesRuleCoupon, 'main_table.coupon_id =' .$salesRuleCoupon.'.coupon_id');
        return $this; // TODO: Change the autogenerated stub
    }
}
