<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $helper = $this->helper(\Magenest\BuyNow\Helper\Data::class); ?>
<?php $formId = $helper->getAddToCartFormId(); ?>
<?php $buttonTit = $helper->getButtonTitle() ?>
<?php $enableGuest = $helper->getConfig('buynow/general/enable_guest');
$customer = $helper->getCustomerId();
$enableBuynow = $helper->getConfig('buynow/general/enable_view');
?>
<?php if($customer == 1 || $enableGuest == 1 && $customer == 0){
    $show = 'block';
}else{
    $show = 'none';
} ?>
<?php $count = $block->getProductDefaultQty() * 1; ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart" style="display: <?php echo $show ?>">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>

                <div class="field qty" style="display: flex">
                    <button type="button" id="decrease-btn"
                            class="decrease">-</button>
                    <script type="text/javascript">

                        require(
                            [
                                'jquery'
                            ],
                            function($) {

                                $("#decrease-btn").on('click',function(){
                                    let count = $('#qty').val();
                                    let tmp;
                                    if(count > 1){
                                        tmp = count - 1;
                                        count = tmp;
                                        $('#qty').val(tmp)
                                    }

                                    console.log(count);

                                });

                            }
                        );


                    </script>

                    <div class="control">

                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $count ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>

                    <button type="button" id="increase-btn"
                            class="increase">+</button>
                    <script type="text/javascript">

                        require(
                            [
                                'jquery'
                            ],
                            function($) {

                                $("#increase-btn").on('click',function(){
                                    let count = $('#qty').val();
                                    let tmp;
                                        count++;
                                        $('#qty').val(count)


                                    console.log(count);

                                });

                            }
                        );


                    </script>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>

                <?php if($enableBuynow == 1){ ?>
                    <div class="buynow-button" >
                        <button type="submit"
                                title="<?= $block->escapeHtml(__($buttonTit)) ?>"
                                id="buy-now"
                                class="action primary buy-now-btn"
                                data-mage-init='
                                {
                                    "Magenest_BuyNow/js/buy-now": {
                                        "form": "#<?= $block->escapeHtml($formId); ?>"
                                    }
                                }
                                '>
                            <span><?= $block->escapeHtml(__($buttonTit)) ?></span>
                        </button>
                    </div>
                <?php } ?>

            </div>

        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<button id="increase"
        class="increase">+</button>
