<?php

namespace Magenest\Checkout\Model\ResourceModel\Coupon;
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'id';


    protected function _construct()
    {
        $this->_init('Magenest\Checkout\Model\Coupon', 'Magenest\Checkout\Model\ResourceModel\Coupon');
    }
    protected function _initSelect()
    {
        parent::_initSelect();
        $salesRuleTable = $this->getTable('salesrule');
        $this->addFieldToSelect('code')
            ->addFieldToSelect('usage_limit')
            ->addFieldToSelect('coupon_id');

        $this->getSelect()
            ->joinLeft($salesRuleTable,'main_table.rule_id = salesrule.rule_id')
            ->joinLeft('salesrule_customer_group', 'main_table.rule_id = salesrule_customer_group.rule_id');
        return $this; // TODO: Change the autogenerated stub
    }

}
