<?php

namespace Magenest\ProductRecommendations\Model\ResourceModel\ProductViewer;

use Magenest\ProductRecommendations\Model\ProductViewer as PostModel;
use Magenest\ProductRecommendations\Model\ResourceModel\ProductViewer as PostResourceModel;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected function _construct()
    {
        $this->_init(PostModel::class, PostResourceModel::class);
    }
    protected function _initSelect()
    {
        parent::_initSelect();
        $customer = $this->getTable('customer_entity');
        $product = $this->getTable('catalog_product_entity');
        $catalogProduct = $this->getTable('catalog_category_product');
        $this->getSelect()
            ->joinLeft($customer, 'main_table.user_id =' .$customer.'.entity_id',['firstname', 'lastname','email'])
            ->joinLeft($product, 'main_table.product_id='.$product.'.entity_id');
        return $this; // TODO: Change the autogenerated stub
    }
}
