<h2>Customer</h2>
<table>
    <tr>
        <th>Avatar</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Phone</th>

    </tr>


        <tr>
            <td><img style="height: 100px" src="<?php echo $block->getAvatar() ?>" /> </td>
            <td><?php echo $block->getFirstname() ?></td>
            <td><?php echo $block->getLastname() ?></td>
            <td><?php echo $block->getEmail() ?></td>
            <td><?php echo $block->getPhone() ?></td>


        </tr>

</table>

<div><h3>You are B2b ?</h3><?php if($block->getB2b() == '1'){
        echo 'Yes';
    }else{
        echo 'No';
    }

    ?></div>
