<div data-bind="scope: 'coupon-listing'" class="scalable">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
                    {
                        "*": {
                            "Magento_Ui/js/core/app": {
                                "components": {
                                    "coupon-listing": {
                                        "component": "Magenest_Customer/js/view/codeList",
                                        "current_page" : "<?= $block->getRequest()->getFullActionName()?>"
                                    }
                                }
                            }
                        }
                    }
</script>
